import * as yaml from 'yaml';
import fs from 'fs';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // bookSidebar: [{ type: 'autogenerated', dirName: 'book' }],
  referenceSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['modules'],
    },
    {
      type: 'category',
      label: 'Basic Concepts',
      items: [
        {
          type: 'category',
          label: 'Primitive Types',
          items: [
            'primitive-types/integers',
            'primitive-types/bool',
            'primitive-types/address',
            'primitive-types/vector',
            'primitive-types/references',
            'primitive-types/tuples',
          ],
        },
        'variables',
        'equality',
        {
          type: 'category',
          label: 'Abort and Assert',
          items: ['abort-and-assert', 'abort-and-assert/clever-errors'],
        },
        {
          type: 'category',
          label: 'Control Flow',
          items: [
            'control-flow',
            'control-flow/conditionals',
            'control-flow/loops',
            'control-flow/labeled-control-flow',
            'control-flow/pattern-matching',
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: ['functions', 'functions/macros'],
        },
        'structs',
        'enums',
        'constants',
        'generics',
        'abilities',
        'uses',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Concepts',
      items: ['method-syntax', 'index-syntax'],
    },
    {
      type: 'category',
      label: 'Tooling',
      items: ['packages', 'unit-testing'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['coding-conventions'],
    },
    {
      type: 'category',
      label: 'Deprecated',
      items: ['friends'],
    },
  ],
};

export default sidebars;
