name: Spelling & Grammar Check

on:
  pull_request:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        # The path to the files to check
        task_name: Markdown
