name: Make sure packages compile

# Set the VERSION variable to use when downloading the binary
# Currently, requires explicit setup, ideally it should be fetched
# automatically
env:
  VERSION: 'v1.24.1'

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Sui
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: MystenLabs/sui
          platform: ubuntu
          tag: 'mainnet-${{ env.VERSION }}'
          cache: enable
          extension: '.tgz'
      # - run: 'which sui'
      - run: 'sui --help'
      - run: 'sui move test --path packages/samples'
      - run: 'sui move test --path packages/reference'
      - run: 'sui move test --path packages/todo_list'
      - run: 'sui move test --path packages/hello_world'
